# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: first-netcore-app
  labels:
    app: dotnet-aks
    component: netcore-app
spec:
  containers:
    - image: jhacontainer.azurecr.io/webapi10:v4
      name: webapi
      ports:
        - containerPort: 80


     
        