# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: first-netcore-app
  labels:
    app: dotnet-aks
    component: netcore-app
spec:
  containers:
    - image: jhacontainer1.azurecr.io/jhalogapi:v1
      name: webapi
      ports:
        - containerPort: 80


     
        