# pod.yml
apiVersion: v1
kind: Pod
metadata:
  name: first-netcore-app
  labels:
    app: dotnet-aks
    component: netcore-app
spec:
  containers:
    - image: jhacontainer.azurecr.io/webapi8:v2
      name: webapi
      ports:
        - containerPort: 80
      volumeMounts:
        - name: varcontainerlogs
          mountPath: /var/log/containers
  volumes:
    - name: varcontainerlogs
      hostPath:
        path: /var/log/containers
     
        