apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      run: webapi
  replicas: 4
  template:
    metadata:
      labels:
        run: webapi
    spec:
      containers:
      - name: webapi
        image: jhacontainer.azurecr.io/webapi10:v5
        ports:
        - containerPort: 80