apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi
spec:
  selector:
    matchLabels:
      run: webapi
  replicas: 2
  template:
    metadata:
      labels:
        run: webapi
    spec:
      containers:
      - name: webapi
        image: jhacontainer1.azurecr.io/jhalogapi:v4
        ports:
        - containerPort: 80