# service.yml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapi
  name: webapi
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    run: webapi
  type: LoadBalancer